src/blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import IndexView, post_detail

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'article/(?P<id>[0-9]+)/$', post_detail, name='post_detail'),
]

src/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^users_list/', include('users_list.urls', namespace='users_list')),
    url(r'^auth/', include('loginsys.urls', namespace='auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/loginsys/urls.py
from django.conf.urls import url
from loginsys import views




urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
]

src/users_list/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import IndexView, UserDetailView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^user_detail/(?P<pk>\d+)/', UserDetailView.as_view(), name='detail')
    # url(r'article/(?P<id>[0-9]+)/$', post_detail, name='post_detail'),
]

src/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class IsActiveManager(models.Manager):

    def get_queryset(self):
        return super(IsActiveManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название категории', unique=True)
    is_active = models.BooleanField(default=True)
    objects = models.Manager()
    active = IsActiveManager()

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    author = models.ForeignKey(User, verbose_name='Пользователь')
    category = models.ForeignKey(Category, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    objects = models.Manager()
    active = IsActiveManager()


    class Meta:
        ordering = ["-created_at"] #cортировка по дате создания в обратном порядке "-"

    def __str__(self):
        # return "{title} | {desc}".format(title=self.title, desc=self.description[:20])   #функция строкового представляния Python
        return self.title

src/loginsys/models.py
from django.db import models

# Create your models here.

src/menu/models.py
from django.db import models
from django.urls import NoReverseMatch
from django.urls import reverse


class MainMenu(models.Model):
    name = models.CharField(max_length=256, verbose_name="Наименование")
    url = models.CharField(max_length=256, verbose_name="Django-URL", help_text="blog:index")
    position = models.IntegerField(default=1000) #цифровое поле ( по стандарту 1000)

    def get_url(self):
        try:
            return reverse(self.url) # преобразование blog:index в ссылку
        except NoReverseMatch:
            return ""

    class Meta:
        ordering = ['position', 'name'] #сортировка
        verbose_name = 'Пункты меню'
        verbose_name_plural = 'Пункт меню'

    def __str__(self):
        return self.name

src/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User

class Department(models.Model):
    name = models.CharField(max_length=300, verbose_name='Отдел')


    def __str__(self):
        return self.name


class Profile(models.Model): #создать новую таблицу в бд
    user = models.OneToOneField(User, on_delete=models.CASCADE) #cвязь пользлвателя и профиля, взаимосвязь при удалении
    patronymic = models.CharField(max_length=150, verbose_name='Отчество')
    department = models.ForeignKey(Department, related_name='users')
    job = models.CharField(max_length=256, blank=True, verbose_name='Должность')
    birthday = models.DateField(blank=True) #blanck - необязательное для заполнения
    mobile_phone = models.CharField(max_length=12, verbose_name='Телефон')
    work_phone = models.CharField(max_length=10, verbose_name='Внутренний телефон', blank=True)
    image = models.ImageField(upload_to="image_users/", verbose_name='Ваше фото', help_text='150x150px', blank=True)
    #TODO: добавить фотографию профиля

# Create your models here.

src/blog/views.py
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Category, Post
# Create your views here.

@method_decorator(login_required, name='dispatch')
class IndexView(ListView):
    template_name = "blog/index.html"
    queryset = Post.active.all()
    context_object_name = "posts"


@login_required
def post_detail(request, id):
    context = {
        'post': get_object_or_404(Post, pk=id)

    }
    return render(request, 'blog/post_detail.html', context)

src/loginsys/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib import auth
# Create your views here.






def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('blog:index')
        else:
            return redirect('auth:login')
    else:
        return render(request, 'loginsys/login.html')



def logout(request):
    auth.logout(request)
    return redirect('auth:login')

src/menu/views.py
from django.shortcuts import render

# Create your views here.

src/users_list/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

@method_decorator(login_required, name='dispatch')
class IndexView(ListView):
    template_name = 'users_list/users_list.html'
    model = User
    context_object_name = "users"


@method_decorator(login_required, name='dispatch')
class UserDetailView(DetailView):
    template_name = 'users_list/user_detail.html'
    model = User
    context_object_name = "user"
    image = "image"

src/templates/blog/index.html
{% extends "master.html" %}

{% block title %}
    Мой блог
{% endblock title %}

{% block content %}

{% for post in posts %}
    <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><a href="{% url "blog:post_detail" post.id %}">{{ post.title }}</a></h3>
          <div class="box-tools pull-right">
            <!-- Buttons, labels, and many other things can be placed here! -->
            <!-- Here is a label for example -->
            <span class="label label-primary">{{ post.category.name }}</span>
          </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body">
          {{ post.description }}
        </div><!-- /.box-body -->
      </div><!-- /.box -->
{% endfor %}



{% endblock content %}



{# <a href="{% url "blog:index" %}?q={{ post.category.id }}"> #}

src/templates/blog/post_detail.html
{% extends "master.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

   <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><a href="{% url "blog:post_detail" post.id %}">{{ post.title }}</a></h3>
          <div class="box-tools pull-right">
            <!-- Buttons, labels, and many other things can be placed here! -->
            <!-- Here is a label for example -->
            <span class="label label-primary">{{ post.category.name }}</span>
          </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body">
          {{ post.description }}
        </div><!-- /.box-body -->
    <div class="box-footer">
    <a href="{% url "blog:index" %}">Назад</a>
    </div>
      </div><!-- /.box -->



{% endblock content %}

src/templates/layouts/footer.html
 <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

src/templates/layouts/head.html
{% load static %}
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}AdminLTE 2 | Starter{% endblock title %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="{% static 'css/skins/skin-blue.min.css' %}">



  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

src/templates/layouts/main_header.html
{% load static %}

<header class="main-header">

    <!-- Logo -->
    <a href="{% url 'blog:index' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">BEST-ELLE</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the messages -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <!-- User Image -->
                        <img src="{% static 'img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                      </div>
                      <!-- Message title and timestamp -->
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <!-- The message -->
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul>
                <!-- /.menu -->
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- /.messages-menu -->

          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- Inner Menu: contains the notifications -->
                <ul class="menu">
                  <li><!-- start notification -->
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                  <!-- end notification -->
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- Tasks Menu -->
          <li class="dropdown tasks-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- Inner menu: contains the tasks -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <!-- Task title and progress text -->
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <!-- The progress bar -->
                      <div class="progress xs">
                        <!-- Change the css width attribute to simulate progress -->
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
                          
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="{% static 'img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->

              <span class="hidden-xs">
                  {{ request.user.username }}</span>
              {% else %}
              <a href="{% url 'auth:login' %}" class="btn btn-success">Войти</a>
              {% endif %}
            </a>
            {% if user.is_authenticated %}
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">

                <p>
                  {{ request.user.last_name }} {{ request.user.first_name }} - {{ request.user.profile.job }}
                  <small>{{ request.user.profile.department.name }}</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'auth:logout' %}" class="btn btn-default btn-flat">Выйти</a>
                </div>
              </li>
            </ul>
            {% endif %}
          </li>
          <!-- Control Sidebar Toggle Button -->
          {% if request.user.is_authenticated %}
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>

src/templates/loginsys/login.html
{% extends 'master.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
        <form action="{% url 'auth:login' %}" method="post">
            {% csrf_token %}

            <input type="text" class="form-control" name="username" placeholder="Username"/>
            <input type="password" class="form-control" placeholder="Password" name="password"/>

              <button type="submit" class="btn btn-primary btn-block btn-flat">Войти</button>

        </form>
</div></div>
    </div>
{% endblock %}

src/templates/master.html
{% load static %}
{% load activeurl %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    {% include 'layouts/head.html' %}
    {% block extra_css %} {% endblock %}
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">

  <!-- Main Header -->
    {% include 'layouts/main_header.html' %}
  <!-- Left side column. contains the logo and sidebar -->
  {% if user.is_authenticated %}
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static  "img/user2-160x160.jpg" %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ request.user.last_name}} {{ request.user.first_name }}</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- search form (Optional) -->
{#      <form action="#" method="get" class="sidebar-form">#}
{#        <div class="input-group">#}
{#          <input type="text" name="q" class="form-control" placeholder="Search...">#}
{#          <span class="input-group-btn">#}
{#              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>#}
{#              </button>#}
{#            </span>#}
{#        </div>#}
{#      </form>#}
      <!-- /.search form -->

      <!-- Sidebar Menu -->
    {% activeurl %}
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Меню:</li>
        <!-- Optionally, you can add icons to the links -->
          {% for item in menu_items %}
{% if item.get_url %}
    <li><a href="{{ item.get_url }}">{{ item.name }}</a></li>
{% endif %}
{% endfor %}
</ul>
    {% endactiveurl %}
    </section>
    <!-- /.sidebar -->
  </aside>
  {% endif %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% block page_title %}{% endblock %}
      </h1>
{#      <ol class="breadcrumb">#}
{#        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>#}
{#        <li class="active">Here</li>#}
{#      </ol>#}
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
{% block content %}
    
{% endblock content %}
    </section>
    <!-- /.content -->
  </div>

  <!-- /.content-wrapper -->

  <!-- Main Footer -->
 {% include 'layouts/footer.html' %}

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3.1.1 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/app.min.js' %}"></script>

{% block extra_javasctipt %}
{% endblock %}

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>

src/templates/users_list/user_detail.html
{% extends "master.html" %}
{% block title %}{% endblock %}

{% block content %}

   <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">{{ user.last_name }} {{ user.first_name }} {{ user.profile.patronymic }}</h3>
          <div class="box-tools pull-right">
            <span class="label label-primary"></span>
          </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <img class="box-body">

            <div>Отдел: {{ user.profile.department.name }}</div>
            <div>Почта: {{ user.email }}</div>
            <div>Мобильный телефон: {{ user.profile.mobile_phone }}</div>
            <div>Рабочий телефон: {{ user.profile.work_phone }}</div>
            <div>День рождения: {{ user.profile.birthday|date:'d.m.Y' }}</div>
            <img src="{{ user.profile.image.url }}">
        </div><!-- /.box-body -->
    <div class="box-footer">
    <a href="{% url "users_list:index" %}">Назад</a>

    </div>
      </div><!-- /.box -->



{% endblock content %}

src/templates/users_list/users_list.html
{% extends 'master.html' %}
{% load static %}

{%  block title %} Справочник сотрудников {% endblock %}

{% block extra_css %}
{#    <link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}">#}
     <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
{% endblock %}

{% block page_title %} Справочник сотрудников {% endblock %}

{% block content %}



       <div class="box box-primary">
        <div class="box-body">
            <div class="table-responsive">
            <table id="datatable" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Отдел</th>
            <th>Электронная почта</th>
            <th>Мобильный телефон</th>
            <th>Внутренний телефон</th>
            <th>Дата рождения</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td><a href="{% url "users_list:detail" user.id %}" >{{ user.last_name }}</a></td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.profile.patronymic }}</td>
            <td>{{ user.profile.department.name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.profile.mobile_phone }}</td>
            <td>{{ user.profile.work_phone }}</td>
            <td>{{ user.profile.birthday|date:'d.m.Y' }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
            </div>

        </div><!-- /.box-body -->
    <div class="box-footer">
    <a href="{% url "blog:index" %}">На главную</a>
    </div>
      </div><!-- /.box -->
{% endblock %}



{% block extra_javasctipt %}
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script>

  $(function () {
    $('#datatable').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });
  });

</script>

{% endblock %}